Repository L1nkWave/Chat, pull requests merged in 2024-02, with the labels that each got.

#16 feature/LWB-8_cors-api-gateway
  .env
  api-gateway/src/main/java/org/linkwave/apigateway/ApiGatewayRouterConfig.java
  api-gateway/src/main/resources/application.yml
  docker-compose.yml
Labels: enhancement, backend

#15 feature/LWF-6_auth
  frontend/.eslintrc.js
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/fonts/gg-sans/gg_sans_Bold.woff
  frontend/public/fonts/gg-sans/gg_sans_Medium.woff
  frontend/public/fonts/gg-sans/gg_sans_Regular.woff
  frontend/public/fonts/gg-sans/gg_sans_Semibold.woff
  frontend/public/icons/form-outline.svg
  frontend/public/icons/index.ts
  frontend/public/icons/lock-outline.svg
  frontend/public/icons/pin-outline.svg
  frontend/public/icons/user-fill.svg
  frontend/public/icons/user-outline.svg
  frontend/public/icons/user-plus-outline.svg
  frontend/public/icons/сurved-arrow-icon.svg
  frontend/public/images/header/headerwave.svg
  frontend/src/api/auth/auth.ts
  frontend/src/api/auth/auth.types.ts
  frontend/src/api/index.ts
  frontend/src/app/chat/page.tsx
  frontend/src/app/layout.tsx
  frontend/src/app/login/page.tsx
  frontend/src/app/page.tsx
  frontend/src/app/sign-in/page.tsx
  frontend/src/app/sign-up/page.tsx
  frontend/src/components/AuthCard/AuthCard.tsx
  frontend/src/components/AuthCard/authCard.types.ts
  frontend/src/components/AuthForm/AuthForm.tsx
  frontend/src/components/AuthForm/authForm.types.ts
  frontend/src/components/AuthForms/SignInForm/SignInForm.tsx
  frontend/src/components/AuthForms/SignUpForm/SignUpForm.tsx
  frontend/src/components/AuthForms/authForms.config.tsx
  frontend/src/components/AuthForms/authForms.utils.ts
  frontend/src/components/Container/Container.tsx
  frontend/src/components/CustomButton/CustomButton.tsx
  frontend/src/components/CustomButton/customButton.config.ts
  frontend/src/components/CustomButton/customButton.types.ts
  frontend/src/components/CustomInput/CustomInput.tsx
  frontend/src/components/CustomInput/customInput.types.ts
  frontend/src/components/Header/Header.tsx
  frontend/src/components/Header/header.types.ts
  frontend/src/components/ThemeToggle/ThemeToggle.tsx
  frontend/src/components/ThemeToggle/themeToggle.config.ts
  frontend/src/lib/features/authSlice.ts
  frontend/src/lib/hooks.ts
  frontend/src/lib/store.ts
  frontend/src/utils/colors.ts
  frontend/tsconfig.json
Labels: enhancement, frontend

#18 feature/LWB-11_use-standard-api-error-structure
  auth-service/src/main/java/org/linkwave/auth/controller/AuthController.java
  auth-service/src/main/java/org/linkwave/auth/dto/ApiError.java
  auth-service/src/main/java/org/linkwave/auth/security/UnAuthorizedAuthenticationEntryPoint.java
  auth-service/src/main/java/org/linkwave/auth/security/filter/JwtTokensRefreshFilter.java
Labels: enhancement, backend

#20 feature/LWF-7_system-notifications
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/index.ts
  frontend/src/api/index.types.ts
  frontend/src/app/layout.tsx
  frontend/src/components/AuthForms/SignInForm/SignInForm.tsx
  frontend/src/components/AuthForms/SignUpForm/SignUpForm.tsx
  frontend/src/components/AuthForms/authForms.config.tsx
  frontend/src/components/AuthForms/authForms.utils.ts
  frontend/src/components/SystemToastContainer/SystemToastContainer.tsx
  frontend/src/components/SystemToastContainer/systemToastContainer.config.ts
  frontend/src/components/SystemToastContainer/systemToastContainer.styles.css
  frontend/src/components/ToastManager/ToastManager.tsx
  frontend/src/redux/store.ts
  frontend/src/utils/formatMessage.ts
Labels: enhancement, frontend

#21 test/LWB-10_ws-routing-unit-testing
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/DefaultRouteHandlerArgumentResolver.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/Payload.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/RouteHandlerArgumentResolver.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/RoutingMessage.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/WebSocketRouterImpl.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/broadcast/SimpleBroadcastManager.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/broadcast/SimpleMessageBroadcast.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/broadcast/WebSocketMessageBroadcast.java
  ws-server/src/main/java/com/chat/wsserver/websocket/routing/parser/TextMessageParser.java
  ws-server/src/test/java/com/chat/wsserver/unit/ChatRoutesBroadcastT.java
  ws-server/src/test/java/com/chat/wsserver/unit/ChatRoutesT.java
  ws-server/src/test/java/com/chat/wsserver/unit/DefaultRouteHandlerArgumentResolverTest.java
  ws-server/src/test/java/com/chat/wsserver/unit/SessionTestUtils.java
  ws-server/src/test/java/com/chat/wsserver/unit/SimpleBroadcastManagerTest.java
  ws-server/src/test/java/com/chat/wsserver/unit/SimpleMessageBroadcastTest.java
  ws-server/src/test/java/com/chat/wsserver/unit/TextMessageParserTest.java
  ws-server/src/test/java/com/chat/wsserver/unit/WebSocketRouterBroadcastTest.java
  ws-server/src/test/java/com/chat/wsserver/unit/WebSocketRouterImplTest.java
  ws-server/src/test/java/com/chat/wsserver/unit/WebSocketRouterTest.java
Labels: enhancement, backend

#24 feature/LW-2_github-actions
  .github/workflows/maven.yml
Labels: enhancement

#23 fix/LWB-12_auth-docs
  auth-service/src/main/resources/static/openapi.json
Labels: documentation

#25 feature/LWB-13_keys-for-tests
  auth-service/src/test/resources/keys/access_private_key.pem
  auth-service/src/test/resources/keys/access_public_key.pem
  auth-service/src/test/resources/keys/refresh_private_key.pem
  auth-service/src/test/resources/keys/refresh_public_key.pem
  user-service/src/test/resources/keys/access_public_key.pem
  ws-server/src/test/resources/access_public_key.pem
Labels: enhancement, backend

#26 fix/LW-3_remove-dependency-graph
  .github/workflows/maven.yml
Labels: temporary

#28 feature/LWB-14_contacts
  api-gateway/src/main/resources/application.yml
  user-service/pom.xml
  user-service/src/main/java/org/linkwave/userservice/UserServiceApplication.java
  user-service/src/main/java/org/linkwave/userservice/controller/RestControllerExceptionHandler.java
  user-service/src/main/java/org/linkwave/userservice/controller/UserController.java
  user-service/src/main/java/org/linkwave/userservice/dto/ContactDto.java
  user-service/src/main/java/org/linkwave/userservice/dto/UserDto.java
  user-service/src/main/java/org/linkwave/userservice/entity/ContactEntity.java
  user-service/src/main/java/org/linkwave/userservice/entity/RoleEntity.java
  user-service/src/main/java/org/linkwave/userservice/entity/UserEntity.java
  user-service/src/main/java/org/linkwave/userservice/exception/ResourceNotFoundException.java
  user-service/src/main/java/org/linkwave/userservice/repository/ContactRepository.java
  user-service/src/main/java/org/linkwave/userservice/repository/UserRepository.java
  user-service/src/main/java/org/linkwave/userservice/security/JwtAuthenticationFilter.java
  user-service/src/main/java/org/linkwave/userservice/security/SecurityConfiguration.java
  user-service/src/main/java/org/linkwave/userservice/service/ContactService.java
  user-service/src/main/java/org/linkwave/userservice/service/UserService.java
  user-service/src/main/java/org/linkwave/userservice/service/impl/ContactServiceImpl.java
  user-service/src/main/java/org/linkwave/userservice/service/impl/DefaultUserService.java
  user-service/src/main/java/org/linkwave/userservice/utils/Headers.java
  user-service/src/main/resources/application.yml
  user-service/src/main/resources/schema.sql
  user-service/src/main/resources/static/api/v1/users/images/placeholder
  user-service/src/main/resources/static/openapi.json
  user-service/src/test/java/org/linkwave/userservice/it/UserControllerTests.java
  user-service/src/test/java/org/linkwave/userservice/unit/ContactServiceImplTest.java
  user-service/src/test/java/org/linkwave/userservice/unit/UserServiceUnitTest.java
  user-service/src/test/java/org/linkwave/userservice/utils/JwtAccessSerializer.java
  user-service/src/test/java/org/linkwave/userservice/utils/Token.java
  user-service/src/test/java/org/linkwave/userservice/utils/TokenGenerator.java
  user-service/src/test/java/org/linkwave/userservice/utils/UsersUtils.java
  user-service/src/test/resources/application.yml
  user-service/src/test/resources/keys/access_private_key.pem
Labels: documentation, enhancement, backend

#33 fix/LWB-19_parameters-resolution
  backend/auth-service/src/main/java/org/linkwave/auth/repository/UserRepository.java
  backend/pom.xml
  backend/user-service/src/main/java/org/linkwave/userservice/repository/ContactRepository.java
  backend/user-service/src/main/java/org/linkwave/userservice/repository/UserRepository.java
  backend/ws-server/src/main/java/org/linkwave/ws/websocket/route/GroupChatRoutes.java
  backend/ws-server/src/main/java/org/linkwave/ws/websocket/routing/DefaultRouteHandlerArgumentResolver.java
  backend/ws-server/src/test/java/org/linkwave/ws/unit/DefaultRouteHandlerArgumentResolverTest.java
  backend/ws-server/src/test/java/org/linkwave/ws/unit/WebSocketRouterBroadcastTest.java
Labels: backend
